name: Generate UML Diagrams

on:
  workflow_dispatch:
  push:
    branches:
      - '*UML_*'
    paths:
      - "**.drawio"
      - '.github/workflows/*'

concurrency:
  group: drawio-export-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-uml-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Check for DrawIO files
        run: |
          if [ -z "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^UML/.*\.drawio$')" ]; then
            echo "No .drawio files found. Exiting with success."
            exit 0
          fi

      - name: Generate DrawIO png files
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: false
          output: ../diagrams

      - name: Commit changes
        run: |
          git status
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Actions: Add generated UML diagrams"
          git push
